apiVersion: v1
kind: Service
metadata:
  name: streaming-server-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: streaming-server
