apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server-deployment
spec:
  replicas: 1 # number of pods to maintain
  selector:
    matchLabels:
      app: streaming-server #pods managed by the deployment
  template:
    metadata:
      labels:
        app: streaming-server
    spec:
      containers:
      - name: streaming-server
        image: balop3e/streaming-server:latest #container image
        ports:
        - containerPort: 8080 #port the container exposes
        volumeMounts:
        - name: storage
          mountPath: /data #mount path for the storage volume
        resources: #resource requests and limits for container
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "200m"
        securityContext: #security settings for the container
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: storage #volume destination
        persistentVolumeClaim:
          claimName: streaming-server-pvc #pvc used for the vlume
