apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server-deployment-server
  namespace: streaming-server
  labels:
    app: streaming-server-server
spec:
  replicas: 1 # number of pods to maintain
  selector:
    matchLabels:
      app: streaming-server-server #pods managed by the deployment
  template:
    metadata:
      labels:
        app: streaming-server-server
    spec:
      containers:
      - name: streaming-server
        image: balop3e/streaming-server:latest #container image
        ports:
        - containerPort: 1935 #port the container exposes
        - containerPort: 8080
        volumeMounts:
        - name: storage-server
          mountPath: /var/lib/streaming #mount path for the storage volume
        resources: #resource requests and limits for container
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "200m"
        # securityContext: #security settings for the container
        #   runAsNonRoot: true
        #   runAsUser: 1000
      volumes:
      - name: storage-server #volume destination
        persistentVolumeClaim:
          claimName: streaming-server-pvc-server #pvc used for the vlume
