apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-server-pvc
spec:
  accessModes:
    - ReadWriteOnce # mounted as read-write
  resources:
    requests:
      storage: 1Gi #amount of storage requested
