apiVersion: v1
kind: Service
metadata:
  name: streaming-server-service-server
  namespace: streaming-server
  labels:
    app: streaming-server-server
spec:
  type: LoadBalancer
  ports:
    - name: "port1935"
      port: 1935
      targetPort: 1935 
      protocol: TCP
    - name: "port8080"
      port: 8080 
      targetPort: 8080 
      protocol: TCP
  selector:
    app: streaming-server-server # identifies the pods this service should route traffic
